version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "2000:2000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always 

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always  