name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # Build backend Docker image
          docker build -t ${{ secrets.DOCKER_USERNAME }}/biorag-backend:latest -f backend.Dockerfile .
          # Build frontend Docker image
          docker build -t ${{ secrets.DOCKER_USERNAME }}/biorag-frontend:latest -f frontend.Dockerfile .
          
          # Push backend image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/biorag-backend:latest
          # Push frontend image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/biorag-frontend:latest
